#![allow(unused)]

mod number_of_1_bits;
mod add_binary;
mod minimum_bit_flips_to_convert_number;
mod hamming_distance;
mod reverse_bits;
mod missing_number;
mod find_the_difference;
mod power_of_two;
mod counting_bits;
mod shuffle_the_array;
mod find_the_xor_of_numbers_which_appear_twice;
mod number_complement;
mod complement_of_base_10_integer;
mod binary_number_with_alternating_bits;
mod binary_prefix_divisible_by_5;
mod number_of_steps_to_reduce_a_number_to_zero;
mod sort_integers_by_the_number_of_1_bits;
mod xor_operation_in_an_array;
mod decode_xored_array;
mod first_letter_to_appear_twice;
mod count_pairs_of_similar_strings;
mod number_of_even_and_odd_bits;
mod sum_of_values_at_indices_with_k_set_bits;
mod minimum_operations_to_collect_elements;
mod prime_number_of_set_bits_in_binary_representation;
mod flipping_an_image;
mod binary_gap;
mod two_out_of_three;
mod find_the_k_or_of_an_array;
mod maximum_strong_pair_xor_1;
mod check_if_bitwise_or_has_trailing_zeroes;
mod number_of_bit_changes_to_make_two_integers_equal;
mod construct_the_minimum_bitwise_array_1;
mod smallest_number_with_all_set_bits;
mod single_number;
mod single_number_2;
mod single_number_3;
mod bitwise_xor_of_all_pairings;
mod largest_combination_with_bitwise_and_greater_than_zero;
mod xor_queries_of_a_subarray;
mod maximum_xor_for_each_query;
mod neighboring_bitwise_xor;
mod shortest_subarray_with_or_at_least_k_1;
mod shortest_subarray_with_or_at_least_k_2;
mod sum_of_two_integers;
mod longest_nice_subarray;
mod find_the_longest_substring_containing_vowels_in_even_counts;
mod minimize_xor;
mod reverse_integer;
mod bitwise_and_of_numbers_range;
mod maximum_product_of_word_lengths;
mod count_triplets_that_can_form_two_arrays_of_equal_xor;
mod find_kth_bit_in_nth_binary_string;
mod minimum_array_end;

pub fn main() {
    maximum_product_of_word_lengths::main();
}
